In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

books = []

# Scrape first 5 pages
for page in range(1, 6):

    url = f"https://books.toscrape.com/catalogue/page-{page}.html"

    response = requests.get(url)

    soup = BeautifulSoup(response.text, "html.parser")

    # Find all books on the page
    products = soup.find_all("article", class_="product_pod")

    for product in products:

        # Title
        title = product.h3.a["title"]

        # Price
        price = product.find("p", class_="price_color").text.strip()

        # Star rating
        rating = product.find("p", class_="star-rating")
        star_rating = rating["class"][1]

        # Availability
        availability = product.find(
            "p", class_="instock availability"
        ).text.strip()

        # Category
        # Open individual book page to get category
        book_url = "https://books.toscrape.com/catalogue/" + product.h3.a["href"]

        book_response = requests.get(book_url)
        book_soup = BeautifulSoup(book_response.text, "html.parser")

        breadcrumb = book_soup.find("ul", class_="breadcrumb")

        category = breadcrumb.find_all("li")[2].text.strip()

        # Store data
        books.append({
            "title": title,
            "price": price,
            "star_rating": star_rating,
            "availability": availability,
            "category": category
        })

# Convert to DataFrame
df = pd.DataFrame(books)

print("Number of books:", len(df))

df.head()

Number of books: 100

,title,price,star_rating,availability,category
0,A Light in the Attic,Â£51.77,Three,In stock,Poetry
1,Tipping the Velvet,Â£53.74,One,In stock,Historical Fiction
2,Soumission,Â£50.10,One,In stock,Fiction
3,Sharp Objects,Â£47.82,Four,In stock,Mystery
4,Sapiens: A Brief History of Humankind,Â£54.23,Five,In stock,History

In [2]:
df

,title,price,star_rating,availability,category
0,A Light in the Attic,Â£51.77,Three,In stock,Poetry
1,Tipping the Velvet,Â£53.74,One,In stock,Historical Fiction
2,Soumission,Â£50.10,One,In stock,Fiction
3,Sharp Objects,Â£47.82,Four,In stock,Mystery
4,Sapiens: A Brief History of Humankind,Â£54.23,Five,In stock,History
...,...,...,...,...,...
95,Lumberjanes Vol. 3: A Terrible Plan (Lumberjan...,Â£19.92,Two,In stock,Sequential Art
96,"Layered: Baking, Building, and Styling Spectac...",Â£40.11,One,In stock,Food and Drink
97,Judo: Seven Steps to Black Belt (an Introducto...,Â£53.90,Two,In stock,Add a comment
98,Join,Â£35.67,Five,In stock,Science Fiction
99,In the Country We Love: My Family Divided,Â£22.00,Four,In stock,Nonfiction

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         100 non-null    object
 1   price         100 non-null    object
 2   star_rating   100 non-null    object
 3   availability  100 non-null    object
 4   category      100 non-null    object
dtypes: object(5)
memory usage: 4.0+ KB

In [4]:

df["price_gdp"]=df["price"].str.replace("Â£","").astype("float64")

In [5]:
df

,title,price,star_rating,availability,category,price_gdp
0,A Light in the Attic,Â£51.77,Three,In stock,Poetry,51.77
1,Tipping the Velvet,Â£53.74,One,In stock,Historical Fiction,53.74
2,Soumission,Â£50.10,One,In stock,Fiction,50.10
3,Sharp Objects,Â£47.82,Four,In stock,Mystery,47.82
4,Sapiens: A Brief History of Humankind,Â£54.23,Five,In stock,History,54.23
...,...,...,...,...,...,...
95,Lumberjanes Vol. 3: A Terrible Plan (Lumberjan...,Â£19.92,Two,In stock,Sequential Art,19.92
96,"Layered: Baking, Building, and Styling Spectac...",Â£40.11,One,In stock,Food and Drink,40.11
97,Judo: Seven Steps to Black Belt (an Introducto...,Â£53.90,Two,In stock,Add a comment,53.90
98,Join,Â£35.67,Five,In stock,Science Fiction,35.67
99,In the Country We Love: My Family Divided,Â£22.00,Four,In stock,Nonfiction,22.00

In [6]:
df["star_rating"].unique()

array(['Three', 'One', 'Four', 'Five', 'Two'], dtype=object)

In [7]:
df["rating"] = (
    df["star_rating"]
    .str.replace("Three", "3")
    .replace("One", "1")
    .replace("Four", "4")
    .replace("Five", "5")
    .replace("Two", "2")
    .astype(int)
)

In [8]:
df["availability"].unique()

array(['In stock'], dtype=object)

In [9]:
df["in_stock"]=df["availability"].map({'In stock':True})
df

,title,price,star_rating,availability,category,price_gdp,rating,in_stock
0,A Light in the Attic,Â£51.77,Three,In stock,Poetry,51.77,3,True
1,Tipping the Velvet,Â£53.74,One,In stock,Historical Fiction,53.74,1,True
2,Soumission,Â£50.10,One,In stock,Fiction,50.10,1,True
3,Sharp Objects,Â£47.82,Four,In stock,Mystery,47.82,4,True
4,Sapiens: A Brief History of Humankind,Â£54.23,Five,In stock,History,54.23,5,True
...,...,...,...,...,...,...,...,...
95,Lumberjanes Vol. 3: A Terrible Plan (Lumberjan...,Â£19.92,Two,In stock,Sequential Art,19.92,2,True
96,"Layered: Baking, Building, and Styling Spectac...",Â£40.11,One,In stock,Food and Drink,40.11,1,True
97,Judo: Seven Steps to Black Belt (an Introducto...,Â£53.90,Two,In stock,Add a comment,53.90,2,True
98,Join,Â£35.67,Five,In stock,Science Fiction,35.67,5,True
99,In the Country We Love: My Family Divided,Â£22.00,Four,In stock,Nonfiction,22.00,4,True

In [10]:
df.isnull().sum()

title           0
price           0
star_rating     0
availability    0
category        0
price_gdp       0
rating          0
in_stock        0
dtype: int64

In [11]:
df.describe()

        price_gdp      rating
count  100.000000  100.000000
mean    34.560700    2.930000
std     14.638531    1.423149
min     10.160000    1.000000
25%     19.897500    2.000000
50%     34.775000    3.000000
75%     47.967500    4.000000
max     58.110000    5.000000

In [12]:
df["rating"] = df["rating"].fillna(df["rating"].mean())

In [13]:
df.isnull().sum()

title           0
price           0
star_rating     0
availability    0
category        0
price_gdp       0
rating          0
in_stock        0
dtype: int64

In [14]:
df.columns

Index(['title', 'price', 'star_rating', 'availability', 'category',
       'price_gdp', 'rating', 'in_stock'],
      dtype='object')

In [15]:
 df['price_inr']= df['price_gdp']*105.50

In [16]:
df

,title,price,star_rating,availability,category,price_gdp,rating,in_stock,price_inr
0,A Light in the Attic,Â£51.77,Three,In stock,Poetry,51.77,3,True,5461.735
1,Tipping the Velvet,Â£53.74,One,In stock,Historical Fiction,53.74,1,True,5669.570
2,Soumission,Â£50.10,One,In stock,Fiction,50.10,1,True,5285.550
3,Sharp Objects,Â£47.82,Four,In stock,Mystery,47.82,4,True,5045.010
4,Sapiens: A Brief History of Humankind,Â£54.23,Five,In stock,History,54.23,5,True,5721.265
...,...,...,...,...,...,...,...,...,...
95,Lumberjanes Vol. 3: A Terrible Plan (Lumberjan...,Â£19.92,Two,In stock,Sequential Art,19.92,2,True,2101.560
96,"Layered: Baking, Building, and Styling Spectac...",Â£40.11,One,In stock,Food and Drink,40.11,1,True,4231.605
97,Judo: Seven Steps to Black Belt (an Introducto...,Â£53.90,Two,In stock,Add a comment,53.90,2,True,5686.450
98,Join,Â£35.67,Five,In stock,Science Fiction,35.67,5,True,3763.185
99,In the Country We Love: My Family Divided,Â£22.00,Four,In stock,Nonfiction,22.00,4,True,2321.000

In [17]:
import sqlite3

conn = sqlite3.connect("books.db")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS categories (
    category_id INTEGER PRIMARY KEY,
    category_name TEXT UNIQUE
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS books (
    book_id INTEGER PRIMARY KEY,
    title TEXT,
    price_gbp REAL,
    price_inr REAL,
    rating INTEGER,
    in_stock INTEGER,
    category_id INTEGER,
    FOREIGN KEY (category_id) REFERENCES categories(category_id)
)
""")

conn.commit()

print("Tables created successfully")

Tables created successfully

In [18]:
df = df.rename(columns={"price_gdp": "price_gbp"})

In [19]:
import sqlite3

conn = sqlite3.connect("books.db")
cursor = conn.cursor()

# Get unique categories
categories = df["category"].unique()

for category in categories:
    cursor.execute(
        "INSERT OR IGNORE INTO categories (category_name) VALUES (?)",
        (category,)
    )

conn.commit()

In [20]:
for _, row in df.iterrows():

    cursor.execute(
        "SELECT category_id FROM categories WHERE category_name = ?",
        (row["category"],)
    )

    category_id = cursor.fetchone()[0]

    cursor.execute("""
        INSERT INTO books
        (title, price_gbp, price_inr, rating, in_stock, category_id)
        VALUES (?, ?, ?, ?, ?, ?)
    """, (
        row["title"],
        row["price_gbp"],
        row["price_inr"],
        row["rating"],
        int(row["in_stock"]),
        category_id
    ))

conn.commit()

In [21]:
df.columns

Index(['title', 'price', 'star_rating', 'availability', 'category',
       'price_gbp', 'rating', 'in_stock', 'price_inr'],
      dtype='object')

In [22]:
query1 = """
SELECT title, rating
FROM books
WHERE rating = 5
"""

result1 = cursor.execute(query1).fetchall()

print(result1)

[('Sapiens: A Brief History of Humankind', 5), ('Set Me Free', 5), ("Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)", 5), ('Rip it Up and Start Again', 5), ('Chase Me (Paris Nights #2)', 5), ('Black Dust', 5), ('Worlds Elsewhere: Journeys Around Shakespeareâ\x80\x99s Globe', 5), ('The Four Agreements: A Practical Guide to Personal Freedom', 5), ('The Elephant Tree', 5), ("Sophie's World", 5), ('Private Paris (Private #10)', 5), ('#HigherSelfie: Wake Up Your Life. Free Your Soul. Find Your Tribe.', 5), ('We Love You, Charlie Freeman', 5), ('Thirst', 5), ('The Inefficiency Assassin: Time Management Tactics for Working Smarter, Not Longer', 5), ("The Activist's Tao Te Ching: Ancient Advice for a Modern Revolution", 5), ('Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Princess Jellyfish 2-in-1 Omnibus #1)', 5), ('Princess Between Worlds (Wide-Awake Princess #5)', 5), ('Join', 5)]

In [23]:
query2 = """
SELECT title, price_gbp
FROM books
ORDER BY price_gbp DESC
"""

result2 = cursor.execute(query2).fetchall()

print(result2)

[('The Death of Humanity: and the Case for Life', 58.11), ('Slow States of Collapse: Poems', 57.31), ('Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991', 57.25), ('The Past Never Ends', 56.5), ('The Pioneer Woman Cooks: Dinnertime: Comfort Classics, Freezer Food, 16-Minute Meals, and Other Delicious Ways to Solve Supper!', 56.41), ('Masks and Shadows', 56.4), ('The Secret of Dreadwillow Carse', 56.13), ('The Electric Pencil: Drawings from Inside State Hospital No. 3', 56.06), ('Birdsong: A Story in Pictures', 54.64), ('Sapiens: A Brief History of Humankind', 54.23), ('The Murder That Never Was (Forensic Instincts #5)', 54.11), ('Judo: Seven Steps to Black Belt (an Introductory Guide for Beginners)', 53.9), ('Tipping the Velvet', 53.74), ('Aladdin and His Wonderful Lamp', 53.13), ("Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)", 52.29), ('Behind Closed Doors', 52.22), ('The Black Maria', 52.15), ('A Light in the Attic', 51.77), ('Libertarianism for Beginners', 51.33), ('Saga, Volume 5 (Saga (Collected Editions) #5)', 51.04), ('Rat Queens, Vol. 3: Demons (Rat Queens (Collected Editions) #11-15)', 50.4), ('We Love You, Charlie Freeman', 50.27), ('Soumission', 50.1), ('The Bulletproof Diet: Lose up to a Pound a Day, Reclaim Energy and Focus, Upgrade Your Life', 49.05), ('orange: The Complete Collection 1 (orange: The Complete Collection #1)', 48.41), ('Sharp Objects', 47.82), ('Private Paris (Private #10)', 47.61), ('Lumberjanes, Vol. 2: Friendship to the Max (Lumberjanes #5-8)', 46.91), ('Online Marketing for Busy Authors: A Step-By-Step Guide', 46.35), ('Lumberjanes, Vol. 1: Beware the Kitten Holy (Lumberjanes #1-4)', 45.61), ('The Natural History of Us (The Fine Art of Pretending #2)', 45.22), ("It's Only the Himalayas", 45.17), ('Without Borders (Wanderlove #1)', 45.07), ('Wall and Piece', 44.18), ('Unseen City: The Majesty of Pigeons, the Discreet Charm of Snails & Other Wonders of the Urban Wilderness', 44.18), ("The Most Perfect Thing: Inside (and Outside) a Bird's Egg", 42.96), ('Spark Joy: An Illustrated Master Class on the Art of Organizing and Tidying Up', 41.83), ('The Art Forger', 40.76), ('Worlds Elsewhere: Journeys Around Shakespeareâ\x80\x99s Globe', 40.3), ('Layered: Baking, Building, and Styling Spectacular Cakes', 40.11), ('Soul Reader', 39.58), ('Security', 39.25), ('The Nameless City (The Nameless City #1)', 38.16), ('Mesaerion: The Best Science Fiction Stories 1800-1849', 37.59), ('How Music Works', 37.32), ('The Gutsy Girl: Escapades for Your Life of Epic Adventure', 37.13), ('The Bear and the Piano', 36.89), ('Political Suicide: Missteps, Peccadilloes, Bad Calls, Backroom Hijinx, Sordid Pasts, Rotten Breaks, and Just Plain Dumb Mistakes in the Annals of American Politics', 36.28), ('Join', 35.67), ('Rip it Up and Start Again', 35.02), ('Black Dust', 34.53), ("You can't bury them all: Poems", 33.63), ('My Paris Kitchen: Recipes and Stories', 33.37), ('The Dirty Little Secrets of Getting Your Dream Job', 33.34), ('Penny Maybe', 33.29), ("The Activist's Tao Te Ching: Ancient Advice for a Modern Revolution", 32.24), ('When We Collided', 31.77), ('Throwing Rocks at the Google Bus: How Growth Became the Enemy of Prosperity', 31.12), ('The Five Love Languages: How to Express Heartfelt Commitment to Your Mate', 31.05), ('Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More', 30.52), ('Reasons to Stay Alive', 26.41), ('Unbound: How Eight Technologies Made Us Human, Transformed Society, and Brought Our World to the Brink', 25.52), ('Chase Me (Paris Nights #2)', 25.27), ('Saga, Volume 6 (Saga (Collected Editions) #6)', 25.02), ('The Mindfulness and Acceptance Workbook for Anxiety: A Guide to Breaking Free from Anxiety, Phobias, and Worry Using Acceptance and Commitment Therapy', 23.89), ('Olio', 23.88), ('The Elephant Tree', 23.82), ('#HigherSelfie: Wake Up Your Life. Free Your Soul. Find Your Tribe.', 23.11), ('The Requiem Red', 22.65), ('The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics', 22.6), ("America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana", 22.5), ('In the Country We Love: My Family Divided', 22.0), ("Shakespeare's Sonnets", 20.66), ('The Inefficiency Assassin: Time Management Tactics for Working Smarter, Not Longer', 20.59), ('Lumberjanes Vol. 3: A Terrible Plan (Lumberjanes #9-12)', 19.92), ('Reskilling America: Learning to Labor in the Twenty-First Century', 19.83), ('The Age of Genius: The Seventeenth Century and the Birth of the Modern Mind', 19.73), ('In a Dark, Dark Wood', 19.63), ('This One Summer', 19.49), ('The Torch Is Passed: A Harding Family Story', 19.09), ('Pop Gun War, Volume 1: Gift', 18.97), ('Unicorn Tracks', 18.78), ('Maude (1883-1993):She Grew Up with the country', 18.02), ('The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull', 17.93), ('The Four Agreements: A Practical Guide to Personal Freedom', 17.66), ('Set Me Free', 17.46), ('Thirst', 17.27), ('The Life-Changing Magic of Tidying Up: The Japanese Art of Decluttering and Organizing', 16.77), ('Tsubasa: WoRLD CHRoNiCLE 2 (Tsubasa WoRLD CHRoNiCLE #2)', 16.28), ("Sophie's World", 15.94), ('Outcast, Vol. 1: A Darkness Surrounds Him (Outcast #1)', 15.44), ('Obsidian (Lux #1)', 14.86), ('Untitled Collection: Sabbath Poems 2014', 14.27), ('On a Midnight Clear', 14.07), ('Mama Tried: Traditional Italian Cooking for the Screwed, Crude, Vegan, and Tattooed', 14.02), ('Starving Hearts (Triangular Trade Trilogy, #1)', 13.99), ('Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Princess Jellyfish 2-in-1 Omnibus #1)', 13.61), ('Princess Between Worlds (Wide-Awake Princess #5)', 13.34), ('In Her Wake', 12.84), ('Patience', 10.16)]

In [24]:
query3 = """
SELECT title, price_gbp
FROM books
ORDER BY price_gbp DESC
LIMIT 10
"""

result3 = cursor.execute(query3).fetchall()

print(result3)

[('The Death of Humanity: and the Case for Life', 58.11), ('Slow States of Collapse: Poems', 57.31), ('Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991', 57.25), ('The Past Never Ends', 56.5), ('The Pioneer Woman Cooks: Dinnertime: Comfort Classics, Freezer Food, 16-Minute Meals, and Other Delicious Ways to Solve Supper!', 56.41), ('Masks and Shadows', 56.4), ('The Secret of Dreadwillow Carse', 56.13), ('The Electric Pencil: Drawings from Inside State Hospital No. 3', 56.06), ('Birdsong: A Story in Pictures', 54.64), ('Sapiens: A Brief History of Humankind', 54.23)]

In [25]:
query4 = """
SELECT DISTINCT category_name
FROM categories
"""

result4 = cursor.execute(query4).fetchall()

print(result4)

[('Add a comment',), ('Art',), ('Business',), ('Childrens',), ('Contemporary',), ('Default',), ('Fantasy',), ('Fiction',), ('Food and Drink',), ('Health',), ('Historical Fiction',), ('History',), ('Horror',), ('Music',), ('Mystery',), ('New Adult',), ('Nonfiction',), ('Philosophy',), ('Poetry',), ('Politics',), ('Romance',), ('Science',), ('Science Fiction',), ('Self Help',), ('Sequential Art',), ('Spirituality',), ('Thriller',), ('Travel',), ('Young Adult',)]

In [26]:
query5 = """
SELECT title, price_gbp
FROM books
WHERE price_gbp BETWEEN 20 AND 30
"""

result5 = cursor.execute(query5).fetchall()

print(result5)

[('The Requiem Red', 22.65), ('The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics', 22.6), ("Shakespeare's Sonnets", 20.66), ('Olio', 23.88), ('Chase Me (Paris Nights #2)', 25.27), ("America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana", 22.5), ('The Elephant Tree', 23.82), ('Reasons to Stay Alive', 26.41), ('#HigherSelfie: Wake Up Your Life. Free Your Soul. Find Your Tribe.', 23.11), ('Unbound: How Eight Technologies Made Us Human, Transformed Society, and Brought Our World to the Brink', 25.52), ('The Mindfulness and Acceptance Workbook for Anxiety: A Guide to Breaking Free from Anxiety, Phobias, and Worry Using Acceptance and Commitment Therapy', 23.89), ('The Inefficiency Assassin: Time Management Tactics for Working Smarter, Not Longer', 20.59), ('Saga, Volume 6 (Saga (Collected Editions) #6)', 25.02), ('In the Country We Love: My Family Divided', 22.0)]

In [27]:
query6 = """
SELECT
    books.title,
    books.rating,
    categories.category_name
FROM books
JOIN categories
ON books.category_id = categories.category_id
ORDER BY books.rating DESC
LIMIT 10
"""

result6 = cursor.execute(query6).fetchall()

print(result6)

[('Sapiens: A Brief History of Humankind', 5, 'History'), ('Set Me Free', 5, 'Young Adult'), ("Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)", 5, 'Sequential Art'), ('Rip it Up and Start Again', 5, 'Music'), ('Chase Me (Paris Nights #2)', 5, 'Romance'), ('Black Dust', 5, 'Romance'), ('Worlds Elsewhere: Journeys Around Shakespeareâ\x80\x99s Globe', 5, 'Nonfiction'), ('The Four Agreements: A Practical Guide to Personal Freedom', 5, 'Spirituality'), ('The Elephant Tree', 5, 'Thriller'), ("Sophie's World", 5, 'Philosophy')]

In [28]:
queries = [
    ("Query 1 - SELECT WHERE", query1, result1),
    ("Query 2 - ORDER BY", query2, result2),
    ("Query 3 - LIMIT", query3, result3),
    ("Query 4 - DISTINCT", query4, result4),
    ("Query 5 - BETWEEN", query5, result5),
    ("Query 6 - JOIN", query6, result6)
]

with open("query_outputs.txt", "w", encoding="utf-8") as f:

    for name, query, output in queries:

        f.write("=" * 60 + "\n")
        f.write(name + "\n")
        f.write("=" * 60 + "\n")

        f.write("SQL Query:\n")
        f.write(query.strip() + "\n\n")

        f.write("Output:\n")
        for row in output:
            f.write(str(row) + "\n")

        f.write("\n")

In [29]:
conn.close()